services:
  - type: web
    name: locketonl
    env: node
    plan: free
    root: apps/main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
