services:
  - type: web
    name: locketonl
    env: node
    plan: free
    buildCommand: npm install && npm run build -w main
    startCommand: cd apps/main && npm start
    envVars:
      - key: NODE_ENV
        value: production
